// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get_profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Returns Rugved Narkar's public portfolio profile: name, focus, bio, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Rugved Narkar",
      title: "Go Backend Developer & Frontend Engineer",
      bio: "Specializes in frontend development, crafting dynamic, visually engaging, and highly responsive websites. Strong foundation in HTML, CSS, JavaScript with expertise in Golang, MongoDB, and Spline for interactive, immersive experiences.",
      email: "narkarrugved100@gmail.com",
      github: "https://github.com/Rugved-dev18"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list_projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var projects = [
  {
    title: "Samudra AI",
    description: "Integrated web platform for the Indian marine community providing real-time ocean data, safety alerts, SOS features, and AI-powered insights for fishermen and marine researchers.",
    tags: ["HTML", "CSS3", "TypeScript"],
    link: "https://samudra-india.vercel.app/"
  },
  {
    title: "Care4Elder \u2013 Elder's Assistant App",
    description: "A compassionate support initiative providing care, assistance, and well-being services for senior citizens.",
    tags: ["CSS3", "TypeScript", "API"],
    link: "https://care4elders-phi.vercel.app/"
  },
  {
    title: "3D Portfolio",
    description: "Creative developer portfolio with immersive 3D elements.",
    tags: ["HTML", "CSS", "JavaScript"]
  },
  {
    title: "To-Do App",
    description: "Full-stack task management application with authentication, CRUD operations, and a sleek dark-themed UI.",
    tags: ["Go", "Gin", "PostgreSQL", "JWT Auth"]
  },
  {
    title: "Animation Portfolio",
    description: "Web animation toolkit showcase with smooth interactions.",
    tags: ["GSAP", "Spline", "React"]
  }
];
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "Lists Rugved's featured portfolio projects with descriptions, tech tags, and live links when available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/list_experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var experience = [
  {
    role: "Open Source Contributor",
    organization: "Open Source Connect India",
    duration: "Dec 2025 \u2013 Present",
    description: "Contributed to the Various DevTools project, fixing accessibility bugs and improving the network inspector UI.",
    tags: ["JavaScript", "CSS", "Git", "Open Source"]
  },
  {
    role: "Campus Ambassador Intern",
    organization: "IIT Bombay - Techfest",
    duration: "Jul 2025 \u2013 Nov 2025",
    description: "Represented IIT Bombay's Techfest on campus through outreach campaigns, engagement drives, and registrations.",
    tags: ["HTML", "CSS", "JavaScript", "Adobe Photoshop"]
  },
  {
    role: "Marketing Intern",
    organization: "Eduveda Academy",
    duration: "Jun 2025 \u2013 Jul 2025",
    description: "Contributed to digital marketing campaigns, content creation, social media management, and campaign analysis.",
    tags: ["Sales", "Advertising", "Student Services"]
  }
];
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "List experience",
  description: "Lists Rugved's professional experience: roles, organizations, durations, and highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/list_skills.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var skills = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "TypeScript",
  "Go",
  "MongoDB",
  "MySQL",
  "Git",
  "GitHub",
  "Bash",
  "VS Code",
  "Figma",
  "Photoshop",
  "Hugging Face",
  "Vercel",
  "Firebase",
  "Markdown",
  "PowerShell"
];
var list_skills_default = defineTool4({
  name: "list_skills",
  title: "List skills",
  description: "Lists Rugved's technical skills and tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
    structuredContent: { skills }
  })
});

// src/lib/mcp/tools/get_contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_default = defineTool5({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Rugved's public contact info and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const contact = {
      email: "narkarrugved100@gmail.com",
      github: "https://github.com/Rugved-dev18"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
      structuredContent: contact
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "rugved-portfolio-mcp",
  title: "Rugved Narkar Portfolio",
  version: "0.1.0",
  instructions: "Tools for exploring Rugved Narkar's public developer portfolio. Use get_profile for a summary, list_projects for featured work, list_experience for roles, list_skills for the tech stack, and get_contact for contact info.",
  tools: [get_profile_default, list_projects_default, list_experience_default, list_skills_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
